on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Build
jobs:

  build:
    name: Build windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get the version
        id: get_version
        shell: bash
        run: |
          echo "version = \"$(git describe --tags --match v[0-9]*)\"" > dvcurator/version.py

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with pyinstaller
        run: pyinstaller win.spec

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/dvcurator_win.exe
          draft: true
