name: Coverage
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install coverage
      - name: Run tests and collect coverage
        run: |
          coverage run -m unittest
          coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
